version: '3.3'
services:
   postgres:
     image: postgres:10
     volumes:
       - ./config/storage/postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: "strong_pass"
       POSTGRES_DB: "redmine"
       PGDATA: "/var/lib/postgresql/data"
     restart: always
   redmine:
     build:
       context: ./Redmine
     image: redmine:custom
     ports:
       - 81:3000
     volumes:
       - ./Redmine/storage/docker_redmine-plugins:/usr/src/redmine/plugins
       - ./Redmine/storage/docker_redmine-themes:/usr/src/redmine/public/themes
       - ./Redmine/storage/docker_redmine-data:/usr/src/redmine/files      
     environment:
       REDMINE_DB_POSTGRES: "postgres"
       REDMINE_DB_USERNAME: "postgres"
       REDMINE_DB_PASSWORD: "strong_pass"
       REDMINE_DB_DATABASE: "redmine"
       REDMINE_SECRET_KEY_BASE: "..."
     restart: always
   gitea:
     build:
       context: ./Gitea      
     image: gitea/gitea:latest
     environment:
       - USER_UID=1000
       - USER_GID=1000
       - ROOT_URL=http://gitea:3000
     restart: always
     volumes:
       - ./Gitea:/data
     ports:
       - "3000:3000"
       - "222:22"
   drone-server:
     build:
       context: ./Drone     
     image: drone/drone:0.8
     ports:
       - 80:8000      
       - 9000
     volumes:
       - ./Drone:/var/lib/drone/
     restart: always
     depends_on:
       - gitea
     environment:
       - DRONE_ADMIN=myadmin
       - DRONE_OPEN=true
       - DRONE_HOST=http://drone-server:8000
       - DRONE_GITEA=true
       - DRONE_GITEA_URL=http://gitea:3000
       - DRONE_SECRET=secret
       - DRONE_NETWORK=gitea_default
   drone-agent:
     image: drone/agent:0.8
     command: agent
     restart: always
     depends_on:
       - drone-server
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     environment:
       - DRONE_SERVER=drone-server:9000
       - DRONE_SECRET=secret    





            
